### ISSUE TITLE
Slow Browser's Javascript Execution at Form Building Time

### ISSUE THREAD

**Issue by overnin** [kobotoolbox/enketo-express#506] opened 2016-05-17 12:57 UTC
Hi,

It appears that browsers (Chrome and FF is worse) are quite slow at building the form with submission data. In total tt takes 25s for Chrome to internally build the submission object, and 1m for for FF. See attached JS execution profile recorded on Chrome. The function **createNamespaceNode** take 75% of the time and  **expressions.step** use 90% of the time. Both functions are from **enketo-xpathjs.js**.

![screen shot 2016-05-17 at 14 31 08](https://cloud.githubusercontent.com/assets/896138/15322847/54d30044-1c3f-11e6-865f-72e3d0236941.png)

Is there anything that could be done to speed this up?

Best,
Olivier

**Comment by MartijnR** [comment] 2016-05-17 15:03
Slow indeed. Thanks for this. You're talking just about the time it takes to load the webform URL in the screenshot, right?

Is this with a particular form? If so, can you send it?

**Comment by overnin** [comment] 2016-05-17 16:42
Yes, i'm talking about the time when one see the enketo spinner. To give an idea all the data (xml form + submission) is downloaded in less than 2s but the page requires an extra 23s of javascript execution to display anything.

Yes it's a particular form, but i'm not allowed to share it publicly. To give you an idea of the size, there is a bit more than 300 different names with a few repeats. The select options have 1000 entries in the form and about the same number in an external_data.csv file. Apart from the basic the type of entry, we use images and geotraces (geoODK).

**Comment by MartijnR** [comment] 2016-05-17 17:09
It is very likely this issue: https://github.com/kobotoolbox/enketo-express/issues/507. I created a separate issue, because I wasn't sure. By now that you mentioned:

> The select options have 1000 entries

it seems the same.

That issue is now fixed in 1.29.3. Can you please check if your issue is fixed as well now?

**Comment by MartijnR** [comment] 2016-05-17 21:03
Please re-open if the issue still persists. Thanks!

**Comment by overnin** [comment] 2016-05-18 08:34
After upgrading to 1.29.3, the loading time got worse, up form 30s to 1minute, for the exact same form.

![screen shot 2016-05-18 at 10 26 15](https://cloud.githubusercontent.com/assets/896138/15352293/c45fc826-1ce3-11e6-851c-480970371dac.png)

Find attached the CPU profile done with Chrome (zipped)
[CPU-20160518T103309.cpuprofile.zip](https://github.com/kobotoolbox/enketo-express/files/269983/CPU-20160518T103309.cpuprofile.zip)

**Comment by MartijnR** [comment] 2016-05-18 15:03
That's very odd. Thanks for checking. Not sure how I can reproduce this yet. Let's see what the graphs [here](https://github.com/enketo/enketo-core-performance-monitor) look like in a few days.

**Comment by MartijnR** [comment] 2016-05-18 15:06
Does the regular form load slowly as well for you? => http://enketo.landmapp.net/::YYYT (I see your server is down at the moment, and probably the form requires authentication anyway)

**Comment by overnin** [comment] 2016-05-18 20:50
Yes the server is down, i'm only using it in debug. True, the access to the
form requires authentication on an ONA instance.

What do you mean by regular form? If you provide one to me, I can quickly
run a test with it.

**Comment by MartijnR** [comment] 2016-05-18 21:20
I mean the non-edit view that is used for collecting data with enketo. So instead of enke.to/edit/::abcd, you'd use enke.to/::abcd or enke.to/x/#abcd (wherever Ona's regular webform button leads you to).

**Comment by s4parke** [comment] 2016-09-01 19:12
I have a form that takes a veeeryy long time to load initially. After profiling I can see it spends a lot of time in the updateCalc() function. I wonder if switching to the native xpath parser would help? We are desperate for any kind of modification that could improve the initial load time.

https://enketo.ona.io/::YF1f

[calc_n_footprint_29.xlsx](https://github.com/kobotoolbox/enketo-express/files/450501/calc_n_footprint_29.xlsx)

**Comment by MartijnR** [comment] 2016-09-07 15:10
Thanks for this. There are probably ways to improve enketo-core code to improve the performance but this kind of work can take a lot of time so it may have to wait until there is funding for it. I'll keep your form to include it in the future, and will add it to our benchmarking suite, so we can track its performance.

Looking at the calculation column of your form, most calculations should be using the native evaluator already. Most importantly pulldata() is using the native evaluator since version 1.32.2 but I wonder if pulldata() can be optimized further when it's used so often on an a static file (maybe it's not caching results when it could). Exceptions are any calculations that include selected(), if(), int(). Those will use the slow JS evaluator. 

I think you may be able to use the default column for the 'calculations' that just contain a constant (decimal).

**Comment by MartijnR** [comment] 2016-09-07 20:58
form source: https://groups.google.com/forum/#!topic/enketo-users/2z0Aoq71YpY

**Comment by MartijnR** [comment] 2016-09-07 21:49
this is a very time-consuming one:

```
( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_poultry/poultry_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_poultry/poultry_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_pork/pork_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_pork/pork_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_beef/beef_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_beef/beef_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_seafood/seafood_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_seafood/seafood_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_dairy/dairy_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_dairy/dairy_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_cheese/cheese_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_cheese/cheese_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_eggs/eggs_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_eggs/eggs_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_wheat/wheat_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_wheat/wheat_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_wheat/wheat_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_wheat/wheat_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_rice/rice_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_rice/rice_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_veg/veg_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_veg/veg_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_fruit/fruit_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_fruit/fruit_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_legumes/legumes_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_legumes/legumes_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_potatoes/potatoes_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_potatoes/potatoes_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_nuts/nuts_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_nuts/nuts_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_coffee/coffee_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_coffee/coffee_weighted_pct_new ) + ( /calc_n_footprint_29/group_food_detailed_US/group_calc_food_alcohol/alcohol_fp_pct  *  /calc_n_footprint_29/group_food_detailed_US/group_calc_food_alcohol/alcohol_weighted_pct_new ) +  /calc_n_footprint_29/group_housing_energy/fp_home_pct_total  +  /calc_n_footprint_29/group_mass_transportation/fp_travel_pct_total  +  /calc_n_footprint_29/group_goods/fp_goods_services_pct_total : 204.094ms
```

**Comment by MartijnR** [comment] 2016-09-07 22:07
@s4parke, I was wrong, calculations are never done natively. This is because of the (unfortunate) required support for arithmetic with dates, e.g. 2014-04-01 + 10. If you don't do fancy stuff with dates in your form (or don't mind wrapping dates inside the `date()` function), you could add `tryNative=true` in FormModel.prototype.evaluate of the enketo core module, around this line: https://github.com/enketo/enketo-core/blob/master/src/js/Form-model.js#L1023

This should speed up loading your form quite a bit (about 3x faster is my guess, but I tested without the media files attached).

**Comment by MartijnR** [comment] 2016-09-07 22:15
It seems that the pulldata() expressions are not cached because of repeats. That could be the next major opportunity for improvement (caching pulldata ()expression results when it's safe to do so).

**Comment by s4parke** [comment] 2016-09-08 12:17
Thanks very much for your quick and thorough response, Martijn! 

The **tryNative=true statement** in made an incredible difference -- this is the performance boost we needed to be able to release the site!!

For anyone else who wants to try this, the file is located in **/enketo-express/node-modules/enketo-core/src/js/Form-model.js** if you are using enketo-express with the enketo-core npm module.

I may be able to further improve the performance by creating a version without the calculations like you identified above. Perhaps that can be done in my theme's JS because it is already pulling totals for a chart widget.

**Comment by s4parke** [comment] 2016-09-08 12:29
Since I'm not using repeats in my form, is there a simple way to force caching for the pulldata() expressions? 

Another performance penalty comes from a series of calculated fields where I needed to check for "null / NaN" and set the value to "0" because if one value in a calculation was "null / NaN", the entire calculation evaluates to "null / NaN":

`
if( ${poultry_fp_consumption_total} >= 0, ${poultry_fp_consumption_total}, 0 )
`

However I seem to remember something in some release notes about this being a workaround for odk-collect, and perhaps it is not needed anymore...

Also, I'm happy to donate this form as an example to your benchmarking suite or other efforts. :)

**Comment by MartijnR** [comment] 2016-09-08 14:53
I like your theme! If you'd like to have a link on the enketo.org front page, let me know and send a logo.

The NaN behaviour might be dealt with by using a more complex XPath expression that filters out empty nodes using a predicate. This would probably require bigger changes in how the XLSForm is structured though (something like `sum(/path/to/group/*[string-length(text()) > 0]`. The release note you saw is not really relevant to this.

After looking further into this I don't think the pulldata() expressions can be cached safely without breaking a lot, even if repeats are not used.

If you want to try swap these lines (in the same evaluate function):

```js
        expr = this.replacePullDataFn( expr, selector, index );
        cacheable = ( original === expr );
```

to 

```js
        cacheable = ( original === expr );  
        expr = this.replacePullDataFn( expr, selector, index );
``

**Comment by MartijnR** [comment] 2016-09-08 17:15
@s4parke Do please make sure you comply with the license: https://github.com/kobotoolbox/enketo-express#license and display 'powered by Enketo' according to the requirements. Thanks!

**Comment by MartijnR** [comment] 2016-11-07 18:46
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Impressive Nitrogen Footprint Calculator (customized Enketo) <a href="https://t.co/Pk2eTjptB6">https://t.co/Pk2eTjptB6</a></p>&mdash; Enketo (@enketo) <a href="https://twitter.com/enketo/status/795698112476184576">November 7, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Closed** 2016-11-07 18:46 UTC
