### ISSUE TITLE
OC only: redirect to thank you page

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#945] opened 2018-02-26 20:25 UTC
Fs view, close, unsaved, cancel -> thank you page

**Comment by MartijnR** [comment] 2018-03-14 17:47
* [ ] check if the postMessage to parentWindow is used correctly in this use case

**Comment by MartijnR** [comment] 2018-03-14 22:27
The issue I found and fixed in `master` was:

When the user clicks 'Leave Anyway', no message is sent to the parentWindow. (did not find an issue when user clicks Cancel). I may have described the original issue incorrectly.

@powen-oc please verify

**Comment by pbowen-oc** [comment] 2018-03-16 23:38
@MartijnR - I'm not able to reproduce the issue now, but I'm pretty sure it was Leave Anyway that caused the problem. It was the form closing and redirecting incorrectly that was the problem, so I think we must have been clicking Leave Anyway not Cancel

**Closed** 2018-03-17 01:06 UTC
Labels: OC, on hold
