### ISSUE TITLE
"=" constraint not working 

### ISSUE THREAD

**Issue by jbonica** [kobotoolbox/enketo-express#572] opened 2016-10-31 15:49 UTC
The constraint to require two fields to agree is no longer working. If the fields do not agree, the error message is displayed but the user can still submit the form. If the two fields are identical, the error message still displays and the user is able to submit the form.

<bind nodeset="full path to node2" constraint= "node2  = node1" jr:constraintMsg="Fields must match" required="true()" type="string"/>

**Comment by MartijnR** [comment] 2016-10-31 16:58
Is this the constraint you are using: `constraint=". = /path/to/node1"`?

**Comment by MartijnR** [comment] 2016-10-31 17:29
Ah, I see the issue. Constraints are still evaluated but the results are ignored. Thanks!

**Comment by MartijnR** [comment] 2016-10-31 22:48
Thanks! Fix is now merged in enketo-express-oc 1.34.1

**Comment by jbonica** [comment] 2016-11-01 17:47
Thanks, Martijn. We'll run the automation later today to confirm fix.

**Comment by jbonica** [comment] 2016-11-01 18:57
Hi Martijn, I just ran our automation and the scenario in which the constraint is violated is now working as expected. However, the constraint is still partially firing even when the fields match. The error message is showing up. The Form cannot be submitted alert is displayed.

**Comment by MartijnR** [comment] 2016-11-01 19:37
Hi Jim,
 
I cannot reproduce that e.g. in https://odk.enke.to/preview?form=http://23.21.114.69/xlsform/downloads/tmpae6c40vy/constraint.xml 

Can you perhaps send me the XForm or XLSForm? Thanks

**Comment by jbonica** [comment] 2016-11-01 19:44
https://ocformqe3.mystudy.me/preview/::YYHK

**Comment by MartijnR** [comment] 2016-11-01 19:53
Thanks!

The remaining issue is with the constraint XPath expression, the constraint should be either:

relative: `constraint = ".  = ../OC.STUDY_SUBJECT_ID"` or
absolute: `constraint=".  = /xform_crf_multi_page/ssid/OC.STUDY_SUBJECT_ID"`

**Closed by MartijnR** 2016-11-01 19:53 UTC
Labels: bug, OC
