### ISSUE TITLE
'This field is required' validation message should be included in translation.json

### ISSUE THREAD

**Issue by piqoni** [kobotoolbox/enketo-express#179] opened 2015-03-30 08:32 UTC
I noticed that 'This field is required' doesn't exist in translation.json .

(workaround was to edit /public/js/webform-combined.min.js)

**Comment by MartijnR** [comment] 2015-03-30 20:24
Thanks!

duplicate of https://github.com/kobotoolbox/enketo-express/issues/142

**Closed by MartijnR** 2015-03-30 20:24 UTC
