### ISSUE TITLE
Grid Theme for Enketo not working on OCHA instance

### ISSUE THREAD

**Issue by mdestaubin** [kobotoolbox/enketo-express#1136] opened 2019-06-11 15:45 UTC
## Description

On OCHA server, when selecting the Grid theme as the form style in the formbuilder it only shows as the default - single page theme.

## Steps to Reproduce

1. Create or open a form in the formbuilder on an account on the OCHA server.
2. Select Grid theme under Form Style
3. Save and (re)deploy form. 
4. Open Form

## Expected behavior 

The form should be in the grid theme style

## Actual behavior 

It is formatted as the default - single page view instead

## Additional details

Forum Post [here](https://community.kobotoolbox.org/t/grid-theme-not-working/3671/5)

**Comment by jnm** [comment] 2019-06-19 23:10
Reproducible locally (note `"themesSupported":[]` in the built `client-config.js`):
<pre>
<font color="#8AE234"><b>john@scrappy</b></font>:<font color="#729FCF"><b>~/Documents/kobo/dockdev/1db/kobo-install</b></font>$ ./run.py -cf ps
Name   Command   State   Ports
------------------------------
<font color="#8AE234"><b>john@scrappy</b></font>:<font color="#729FCF"><b>~/Documents/kobo/dockdev/1db/kobo-install</b></font>$ sudo rm -fr ../kobo-docker/.vols/enketo_express/
[sudo] password for john: 
<font color="#8AE234"><b>john@scrappy</b></font>:<font color="#729FCF"><b>~/Documents/kobo/dockdev/1db/kobo-install</b></font>$ ./run.py -cf up enketo_express &amp;
[1] 21031
<font color="#8AE234"><b>john@scrappy</b></font>:<font color="#729FCF"><b>~/Documents/kobo/dockdev/1db/kobo-install</b></font>$ <font color="#C4A000">WARNING</font>: Found orphan containers (1db_redis_main_1, 1db_redis_cache_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating 1db_enketo_express_1 ... <font color="#4E9A06">done</font>
Attaching to 1db_enketo_express_1
<font color="#06989A">enketo_express_1  |</font> *** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
<font color="#06989A">enketo_express_1  |</font> *** Running /etc/my_init.d/01_enketo_express_copy_config.bash...
<font color="#06989A">enketo_express_1  |</font> Copying the read-only configuration template into place at `/srv/src/enketo_express/config/config.json`.
<font color="#06989A">enketo_express_1  |</font> *** Running /etc/my_init.d/01_setup_enketo.bash...
<font color="#06989A">enketo_express_1  |</font> sha1sum: /srv/src/enketo_express/checksum/config.json.sha1: No such file or directory
<font color="#06989A">enketo_express_1  |</font> cat: /srv/src/enketo_express/checksum/last_build_commit.txt: No such file or directory
<font color="#06989A">enketo_express_1  |</font> Grunt needs to be run!
<font color="#06989A">enketo_express_1  |</font> Running &quot;shell:clean-locales&quot; (shell) task
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;i18next:locales&quot; (i18next) task
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;widgets&quot; task
<font color="#06989A">enketo_express_1  |</font> File public/js/build/widgets.js created
<font color="#06989A">enketo_express_1  |</font> File app/views/styles/component/_widgets.scss created
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;shell:clean-css&quot; (shell) task
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;system-sass-variables:create&quot; (system-sass-variables) task
<font color="#06989A">enketo_express_1  |</font> File app/views/styles/component/_system_variables.scss created
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;sass:compile&quot; (sass) task
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;shell:clean-js&quot; (shell) task
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;client-config-file:create&quot; (client-config-file) task
<font color="#06989A">enketo_express_1  |</font> File public/js/build/client-config.js created
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;widgets&quot; task
<font color="#06989A">enketo_express_1  |</font> File public/js/build/widgets.js created
<font color="#06989A">enketo_express_1  |</font> File app/views/styles/component/_widgets.scss created
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;shell:rollup&quot; (shell) task
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; node-resolve: setting options.module is deprecated, please override options.mainFields instead
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; node-resolve: setting options.main is deprecated, please override options.mainFields instead
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; public/js/src/enketo-webform.js → public/js/build/enketo-webform-bundle.js...
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; (!) Circular dependency: public/js/src/module/gui.js -&gt; node_modules/enketo-core/src/js/print.js -&gt; public/js/src/module/gui.js
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; created public/js/build/enketo-webform-bundle.js in 9s
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; public/js/src/enketo-webform-edit.js → public/js/build/enketo-webform-edit-bundle.js...
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; (!) Circular dependency: public/js/src/module/gui.js -&gt; node_modules/enketo-core/src/js/print.js -&gt; public/js/src/module/gui.js
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; created public/js/build/enketo-webform-edit-bundle.js in 8s
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; public/js/src/enketo-webform-view.js → public/js/build/enketo-webform-view-bundle.js...
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; (!) Circular dependency: public/js/src/module/gui.js -&gt; node_modules/enketo-core/src/js/print.js -&gt; public/js/src/module/gui.js
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; created public/js/build/enketo-webform-view-bundle.js in 10.5s
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; public/js/src/enketo-offline-fallback.js → public/js/build/enketo-offline-fallback-bundle.js...
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; created public/js/build/enketo-offline-fallback-bundle.js in 40ms
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;shell:ie11polyfill&quot; (shell) task
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; % Total    % Received % Xferd
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; Average Speed   Time    Time     Time  Current
<font color="#06989A">enketo_express_1  |</font> &gt;&gt;                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; 100 93157  1
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; 00 93157    0     0   183k      0 --:--:-- --:--:-- --:--:--  183k
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;shell:babel&quot; (shell) task
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> WARNING: We noticed you&apos;re using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`&apos;s `dependencies` section. If it doesn&apos;t, you need to run one of the following commands:
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>   npm install --save core-js@2    npm install --save core-js@3
<font color="#06989A">enketo_express_1  |</font>   yarn add core-js@2              yarn add core-js@3
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; [BABEL] Note: The code generator has deoptimised the styling of /srv/src/enketo_express/public/js/build/enketo-webform-bundle.js as it exceeds the max of 500KB.
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> WARNING: We noticed you&apos;re using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`&apos;s `dependencies` section. If it doesn&apos;t, you need to run one of the following commands:
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>   npm install --save core-js@2    npm install --save core-js@3
<font color="#06989A">enketo_express_1  |</font>   yarn add core-js@2              yarn add core-js@3
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; [BABEL] Note: The code generator has deoptimised the styling of /srv/src/enketo_express/public/js/build/enketo-webform-edit-bundle.js as it exceeds the max of 500KB.
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> WARNING: We noticed you&apos;re using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`&apos;s `dependencies` section. If it doesn&apos;t, you need to run one of the following commands:
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>   npm install --save core-js@2    npm install --save core-js@3
<font color="#06989A">enketo_express_1  |</font>   yarn add core-js@2              yarn add core-js@3
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; [BABEL] Note: The code generator has deoptimised the styling of /srv/src/enketo_express/public/js/build/enketo-webform-view-bundle.js as it exceeds the max of 500KB.
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> WARNING: We noticed you&apos;re using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`&apos;s `dependencies` section. If it doesn&apos;t, you need to run one of the following commands:
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>   npm install --save core-js@2    npm install --save core-js@3
<font color="#06989A">enketo_express_1  |</font>   yarn add core-js@2              yarn add core-js@3
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;shell:browserify&quot; (shell) task
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; npx: installed 140 in 8.014s
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; npx: installed 140 in 3.332s
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; npx: installed 140 in 3.349s
<font color="#06989A">enketo_express_1  |</font> &gt;&gt; npx: installed 140 in 3.322s
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Running &quot;terser:all&quot; (terser) task
<font color="#06989A">enketo_express_1  |</font> File &quot;public/js/build/enketo-webform-bundle.min.js&quot; created.
<font color="#06989A">enketo_express_1  |</font> File &quot;public/js/build/enketo-webform-edit-bundle.min.js&quot; created.
<font color="#06989A">enketo_express_1  |</font> File &quot;public/js/build/enketo-webform-view-bundle.min.js&quot; created.
<font color="#06989A">enketo_express_1  |</font> File &quot;public/js/build/enketo-offline-fallback-bundle.min.js&quot; created.
<font color="#06989A">enketo_express_1  |</font> File &quot;public/js/build/enketo-webform-ie11-bundle.min.js&quot; created.
<font color="#06989A">enketo_express_1  |</font> File &quot;public/js/build/enketo-webform-edit-ie11-bundle.min.js&quot; created.
<font color="#06989A">enketo_express_1  |</font> File &quot;public/js/build/enketo-webform-view-ie11-bundle.min.js&quot; created.
<font color="#06989A">enketo_express_1  |</font> File &quot;public/js/build/enketo-offline-fallback-ie11-bundle.min.js&quot; created.
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Done.
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Execution Time (2019-06-19 22:30:10 UTC-0)
<font color="#06989A">enketo_express_1  |</font> shell:rollup       28.1s  ▇▇▇▇▇ 11%
<font color="#06989A">enketo_express_1  |</font> shell:babel          57s  ▇▇▇▇▇▇▇▇▇▇ 22%
<font color="#06989A">enketo_express_1  |</font> shell:browserify   30.1s  ▇▇▇▇▇▇ 11%
<font color="#06989A">enketo_express_1  |</font> terser:all        2m 24s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 55%
<font color="#06989A">enketo_express_1  |</font> Total 4m 22s
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> Saving current commit...
<font color="#06989A">enketo_express_1  |</font> Saving config hash...
<font color="#06989A">enketo_express_1  |</font> Creating .not-empty files
<font color="#06989A">enketo_express_1  |</font> *** Running /etc/my_init.d/10_syslog-ng.init...
<font color="#06989A">enketo_express_1  |</font> Jun 19 22:34:32 a86b26b7bfe7 syslog-ng[277]: syslog-ng starting up; version=&apos;3.5.6&apos;
<font color="#06989A">enketo_express_1  |</font> Jun 19 22:34:33 a86b26b7bfe7 syslog-ng[277]: EOF on control channel, closing connection;
<font color="#06989A">enketo_express_1  |</font> *** Running /etc/rc.local...
<font color="#06989A">enketo_express_1  |</font> *** Booting runit daemon...
<font color="#06989A">enketo_express_1  |</font> *** Runit started as PID 283
<font color="#06989A">enketo_express_1  |</font> Jun 19 22:34:33 a86b26b7bfe7 cron[288]: (CRON) INFO (pidfile fd = 3)
<font color="#06989A">enketo_express_1  |</font> Jun 19 22:34:33 a86b26b7bfe7 cron[288]: (CRON) INFO (Running @reboot jobs)
<font color="#06989A">enketo_express_1  |</font> [PM2][Initialization] Environment variable HOME (Linux) or HOMEPATH (Windows) are not set!
<font color="#06989A">enketo_express_1  |</font> [PM2][Initialization] Defaulting to /etc/.pm2
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>                         -------------
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> __/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
<font color="#06989A">enketo_express_1  |</font>  _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
<font color="#06989A">enketo_express_1  |</font>   _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
<font color="#06989A">enketo_express_1  |</font>    _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
<font color="#06989A">enketo_express_1  |</font>     _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
<font color="#06989A">enketo_express_1  |</font>      _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
<font color="#06989A">enketo_express_1  |</font>       _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
<font color="#06989A">enketo_express_1  |</font>        _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
<font color="#06989A">enketo_express_1  |</font>         _\///______________\///______________\///__\///////////////__
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>                           Runtime Edition
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>         PM2 is a Production Process Manager for Node.js applications
<font color="#06989A">enketo_express_1  |</font>                      with a built-in Load Balancer.
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>                 Start and Daemonize any application:
<font color="#06989A">enketo_express_1  |</font>                 $ pm2 start app.js
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>                 Load Balance 4 instances of api.js:
<font color="#06989A">enketo_express_1  |</font>                 $ pm2 start api.js -i 4
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>                 Monitor in production:
<font color="#06989A">enketo_express_1  |</font>                 $ pm2 monitor
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>                 Make pm2 auto-boot at server restart:
<font color="#06989A">enketo_express_1  |</font>                 $ pm2 startup
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>                 To go further checkout:
<font color="#06989A">enketo_express_1  |</font>                 http://pm2.io/
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font>                         -------------
<font color="#06989A">enketo_express_1  |</font> 
<font color="#06989A">enketo_express_1  |</font> pm2 launched in no-daemon mode (you can add DEBUG=&quot;*&quot; env variable to get more messages)
<font color="#06989A">enketo_express_1  |</font> 2019-06-19T22:34:34: PM2 log: Launching in no daemon mode
<font color="#06989A">enketo_express_1  |</font> 2019-06-19T22:34:34: PM2 log: [PM2] Starting /srv/src/enketo_express/app.js in fork_mode (1 instance)
<font color="#06989A">enketo_express_1  |</font> 2019-06-19T22:34:34: PM2 log: App [enketo:0] starting in -fork mode-
<font color="#06989A">enketo_express_1  |</font> 2019-06-19T22:34:34: PM2 log: App [enketo:0] online
<font color="#06989A">enketo_express_1  |</font> 2019-06-19T22:34:34: PM2 log: [PM2] Done.
<font color="#06989A">enketo_express_1  |</font> 2019-06-19T22:34:34: PM2 log: ┌──────────┬────┬─────────┬──────┬─────┬────────┬─────────┬────────┬─────┬───────────┬──────┬──────────┐
<font color="#06989A">enketo_express_1  |</font> │ App name │ id │ version │ mode │ pid │ status │ restart │ uptime │ cpu │ mem       │ user │ watching │
<font color="#06989A">enketo_express_1  |</font> ├──────────┼────┼─────────┼──────┼─────┼────────┼─────────┼────────┼─────┼───────────┼──────┼──────────┤
<font color="#06989A">enketo_express_1  |</font> │ enketo   │ 0  │ 1.77.0  │ fork │ 298 │ online │ 0       │ 0s     │ 0%  │ 28.6 MB   │ root │ disabled │
<font color="#06989A">enketo_express_1  |</font> └──────────┴────┴─────────┴──────┴─────┴────────┴─────────┴────────┴─────┴───────────┴──────┴──────────┘
<font color="#06989A">enketo_express_1  |</font> 2019-06-19T22:34:34: PM2 log:  Use `pm2 show &lt;id|name&gt;` to get more details about an app
<font color="#06989A">enketo_express_1  |</font> 2019-06-19T22:34:34: PM2 log: [--no-daemon] Continue to stream logs
<font color="#06989A">enketo_express_1  |</font> 2019-06-19T22:34:34: PM2 log: [--no-daemon] Exit on target PM2 exit pid=287
<font color="#06989A">enketo_express_1  |</font> 22:34:36 0|enketo  | Worker 4 ready for duty at port 8005! (environment: production)
<font color="#06989A">enketo_express_1  |</font> 22:34:36 0|enketo  | Worker 2 ready for duty at port 8005! (environment: production)
<font color="#06989A">enketo_express_1  |</font> 22:34:36 0|enketo  | Worker 3 ready for duty at port 8005! (environment: production)
<font color="#06989A">enketo_express_1  |</font> 22:34:36 0|enketo  | Worker 1 ready for duty at port 8005! (environment: production)

<font color="#8AE234"><b>john@scrappy</b></font>:<font color="#729FCF"><b>~/Documents/kobo/dockdev/1db/kobo-install</b></font>$ cat ../kobo-docker/.vols/enketo_express/build/js/client-config.js ; echo
export default {&quot;googleApiKey&quot;:&quot;&quot;,&quot;maps&quot;:[{&quot;name&quot;:&quot;streets&quot;,&quot;tiles&quot;:[&quot;https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png&quot;],&quot;attribution&quot;:&quot;© &lt;a href=\&quot;http://openstreetmap.org\&quot;&gt;OpenStreetMap&lt;/a&gt; | &lt;a href=\&quot;www.openstreetmap.org/copyright\&quot;&gt;Terms&lt;/a&gt;&quot;}],&quot;modernBrowsersURL&quot;:&quot;modern-browsers&quot;,&quot;supportEmail&quot;:&quot;support@kobotoolbox.org&quot;,&quot;themesSupported&quot;:[],&quot;defaultTheme&quot;:&quot;kobo&quot;,&quot;languagesSupported&quot;:[&quot;ar&quot;,&quot;cs&quot;,&quot;de&quot;,&quot;el&quot;,&quot;en&quot;,&quot;es&quot;,&quot;fa&quot;,&quot;fi&quot;,&quot;fr&quot;,&quot;hi&quot;,&quot;it&quot;,&quot;lo&quot;,&quot;nl&quot;,&quot;no&quot;,&quot;pl&quot;,&quot;pt&quot;,&quot;ro&quot;,&quot;ru&quot;,&quot;sk&quot;,&quot;sv&quot;,&quot;sw&quot;,&quot;vi&quot;,&quot;zh&quot;],&quot;timeout&quot;:300000,&quot;submissionParameter&quot;:{&quot;name&quot;:&quot;&quot;},&quot;basePath&quot;:&quot;&quot;,&quot;repeatOrdinals&quot;:false,&quot;validateContinuously&quot;:false,&quot;validatePage&quot;:true,&quot;textMaxChars&quot;:2000};
<font color="#8AE234"><b>john@scrappy</b></font>:<font color="#729FCF"><b>~/Documents/kobo/dockdev/1db/kobo-install</b></font>$ 
</pre>

**Comment by jnm** [comment] 2019-06-20 03:16
Closing in favor of https://github.com/kobotoolbox/enketo-express/issues/477, which I'll have to move manually to https://github.com/enketo/enketo-express/

**Closed by jnm** 2019-06-20 03:16 UTC
