### ISSUE TITLE
File to import not found or unreadable

### ISSUE THREAD

**Issue by adissadis** [kobotoolbox/enketo-express#379] opened 2016-01-05 11:08 UTC
Hi, i want to build enketo-express locally by using manual build. I already run until step 6 and when i want to build with `grunt` from the project root, my build had a warning:
![image](https://cloud.githubusercontent.com/assets/2520159/12113603/5a759862-b3d6-11e5-9e8f-f581c8d67cba.png)
I think this is because they cant find the modules. But i don't know how to resolve this.

When i try to build using `grunt --force`, its worked but the issue come when i want to run `npm start`:
![image](https://cloud.githubusercontent.com/assets/2520159/12113672/d5dfe174-b3d6-11e5-93fc-bf74c9aabf34.png)

Do you guys know what i'm missing? I followed all the manual step until stuck at the final step.

Thank you!

**Comment by MartijnR** [comment] 2016-01-05 16:50
1. I think `npm install` failed. Try deleting the node_modules folder and running `npm install` again. 

2. Redis installation failed as well. Not sure how to help there. You're using [these instructions](http://blog.enketo.org/install-enketo-production-ubuntu/)? Did you conduct the little tests? They probably fail too.

Feel free to keep adding to this thread. I'm closing it for now because it's probably not a bug.

**Closed by MartijnR** 2016-01-05 16:50 UTC

**Comment by adissadis** [comment] 2016-01-06 04:19
Hi @MartijnR thanks for your help. My problem caused from Redis installation as you thought. I haven't set redis server before run grunt. After i set redis server, `grunt` process went well.

I tried to remove node-module as you said and running `npm install` again but i got this error:
![image](https://cloud.githubusercontent.com/assets/2520159/12134861/59b6a2e6-b466-11e5-82af-fedc5c22122e.png)

And when i tried to `npm start` i found that in my node_modules folder is missing libxslt: 
![image](https://cloud.githubusercontent.com/assets/2520159/12134871/8aaf5424-b466-11e5-9ed9-42ba006cea77.png)

So i run `npm install libxslt` but found an error again in the end of the process:
![image](https://cloud.githubusercontent.com/assets/2520159/12134877/ab5b14e2-b466-11e5-86b9-6577ce3382cf.png)

I already deleted node_modules several time and tried to run both `npm install` or `npm install --production` and still find this error.

**Comment by MartijnR** [comment] 2016-01-06 15:42
Ah yes, this module can be problematic (won't work on OS X either). There is probably some dependency that is not compatible. I see your npm version is 3.5.2. For other reasons, this version is not yet supported (problems with generating css files). Try downgrading npm and see if this resolves the libxslt issue.

I think like this:

`npm install -g npm@2.14.7` (this is the version that I think is still bundled with node 4.x unless it recently changed).
