### ISSUE TITLE
UI language on iOS not switching?

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/enketo-express#836] opened 2017-10-10 16:04 UTC
> I am trying to access an Enketo webform in Swedish in an iOS browser where the device's localized language is set to Swedish. However, the webform UI, i.e. Submit, appear in English rather than Swedish, the language I would expect. This occurs regardless of web browser. It has been tested on Safari, Chrome and Photon. This occurs for all iPads and iPhones. It occurs regardless of version, as I have tested on iOS 10 or iOS 11.

> However, when the same form is accessed on a Windows computer or Android device, the UI appears in the device's localized language of Swedish. Is a multi-language Enketo UI supported on iOS operating systems? Or any ideas why this is occurring and how it might be fixed?

**Comment by MartijnR** [comment] 2017-10-11 16:55
This issue may not be present on iOS11.

**Comment by msschroeder** [comment] 2017-10-27 09:18
The issue is still persistent on iOS11.

**Comment by niklaslj** [comment] 2017-10-28 13:12
The difference between IOS and the other is the bowsers use of the request header “Accept-Language:”
IOS sends “Accept-Language: sv-se”
Other sends “Accept-Language: sv, en-US;q=0.8, …”

I made an small test program and “Accept-Language: sv” works fine while “Accept-Language: sv-se” falls back to English (or more correctly "no locale").

So Enketo cannot handle the language setting “sv-se” although is a correct language code.

When testing other language codes like “de-CH” German in Schweiz or “es-ve” Spanish in Venezuela or “sw-KE” Kiswahili in Kenya they all falls back to English. As far as I can see "en-US" and "en-GB" is not handled either, it just falls back to "no locale"..

In a perfect world a change to “Accept-Language: sv-se,sv;q=0.8,en;q=0.6” for IOS in Sweden would handle the situation but I don’t think  we can make Apple to change this…

So the suggested solution is either an addition of logic in the language handler or (maybe more correct) a plain addition of the locale "sv-se" as a duplicate of the "se" locale.

**Comment by niklaslj** [comment] 2017-10-28 13:59
An additional comment:
The language code is interpered case sensitive in Enketo. This dos not follow the rules for languages tags in RFC 5646.
"Accept-Language: SV" does not work. And both "sv-se" and "sv-SE" is commonly used i various documents."
Digging a bit deeper in RFC 5646 I realize that a valid language tag may consist of a series of sub tags with more or less public meaning. (Including sorting and characterset)

So I change my opinon about the best solution: The language parsing in Enketo should be changed to  use the primary language code ie "sv" and only use other sub-tags when relevant to Enketo. 
The language code must also be case insensitive. Assumes the module "i18next" that is used for language parsing can handle this?

A quick temporary fix for IOS addning the "sv-se" locale would however be welcome!

**Comment by MartijnR** [comment] 2017-10-30 16:36
Thanks a lot for your investigation! The way Enketo is meant to work to ignore the second part of the language code if it exists (so for "sv-se", use "se" only, as we don't have support for the dialects and are no planning to add this). Indeed this should be case-insensitive. I'll try to have a look this week where this is going wrong. 

* [ ] reproduce
* [ ] upgrade i18next to see if that resolves it
* [ ] fix in Enketo or file bug report in one of the i18next libraries

**Comment by niklaslj** [comment] 2017-10-30 23:23
After some digging in i18next it seems that a adding a simple option might do the trick.

In  i18next.init(..) located in enketo-express/config/express.js, line 42:
Add the option "load: 'languageOnly'" to only use the language code, disregarding the region sub tag.
You might also add the option "lowerCaseLng: true" to secure case-insensitive language code handling.

Please note that I have not tested the above suggestion. I do not have a test environment to run Enketo (yet) so this is just a theory after reading the documention and poking around in the source code of i18next. 

I was poking in the lastest version of i18next (10.0.6) but these option seems to work the same in 8.4.0 (8.4.x is specified i Enketo). So I would try adding the options before changing version. You never now what suprices a new version would give you :)

I found it very easy to test various language codes by browsing to https://ee.kobotoolbox.org (or https://enketo.ona.io). No forms had to be involved and I could  test language codes by adding parameter "lang" to the url. I was able to verify that the language code "sv" really switches to swedish by browsing to "https://ee.kobotoolbox.org/?lang=sv" using an iPhone.

Please let me know I can help you any further in this matter!

**Comment by MartijnR** [comment] 2017-10-31 16:32
Great. Thank you! The `lang` query parameter might not help to reproduce the "sv-se" problem, but changing browser locale might.

**Comment by niklaslj** [comment] 2017-10-31 18:28
Sorry, do not follow you. For me the lang parameter worked fine to reproduce the switch problem?

Try https://ee.kobotoolbox.org?lang=sv (displays in swedish) and https://ee.kobotoolbox.org?lang=sv-se (displays in english), also verfify ?lang=de (german) vs ?lang=de_CH ( english). Is that not what you get?

I have previously documented what "Accept-Language:" IOS vs Win10 browsers sends in the request:
IOS Safari: "sv-se" for swedish IOS and "en-us" for american IOS.
Win10 Chrome: "sv,en-US;q=0.9,en;q=0.8,nb;q=0.7,da;q=0.6,is;q=0.5" for swedish Chrome

I have  "Accept-Language:" for several more browsers and OS but the pattern is identical: 
IOS always only sends the single language-region language code while modern browsers sends a sequence of language codes with prioritation info (q=0.9). For modern browsers Enketo finds at least one language code in the list that fits.  IOS only sends one code that always includes the region and Enkento fails to find that code in its translations.

So my suggestion for correcting the bug is to add the "load: 'languageOnly'" options in the init of i18next and then try the above four urls to verify the solution. If both "sv" and "sv-se" gives swedish and both "de" and "de-CH" gives german I would assume the problem is solved.

But maybe have I missed something?

**Comment by MartijnR** [comment] 2017-10-31 19:21
Ah yes, you may very well be right that accept-language headers and query parameters are treated the same. I haven't tried reproducing yet. Thanks!

**Comment by niklaslj** [comment] 2017-10-31 22:24
Sorry for the flame in my previous comment! I was only happy to find this shortcut for easier debugging.

Yes, i18Next is set up to accept query param `lang` before header `Accept-Language:` for language settings. It was when reading part of the source code of i18next and the setup of i18next in Enketo I realized it could be used as a shortcut to reproduce the bug and also to indicate if a solution is working.
But of cource it can only be used as an quick indicator, test with real browsers must verify.

The `lang` query actually works for forms as well: https://enketo.ona.io/x/?lang=sv#YNI6 gives a form with Swedish UI but it can not be used as a production fix.  The url is rewritten by Enketo removing the query part so when reloading the page the UI language turns back to English.

**Closed** 2017-11-02 16:54 UTC
Labels: bug, KoBo

**Comment by MartijnR** [comment] 2017-11-02 16:55
Thanks! Your configuration suggestion solved this perfectly.

**Comment by niklaslj** [comment] 2017-11-02 17:28
Great! Confirm that I get Swedish in my IOS-devices!
Thanks for fixing this so swift!
